from jose import JWTError, jwt
from security import SECRET_KEY, JWT_ALGORITHM

token = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsidXNlcm5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AYmlibGlva2VpYS5jb20ifSwiZXhwIjoxNjUyODA2NTg5fQ.NUtLFaJ7V5tLhJVD9u39RHzA5YyzOwBMjpJgTe7PE99FKCWg7ARwpd0hWoQzQ17fItxc1oujUu8bSVLiq-dfjQ"


payload = jwt.decode(token, SECRET_KEY, algorithms=[JWT_ALGORITHM])