"""AcessPoint

Revision ID: 1e5a1306e61e
Revises: ea965982f313
Create Date: 2022-06-06 16:13:15.104769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e5a1306e61e'
down_revision = 'ea965982f313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorship',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('authority_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('relation', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('publicationyear', mysql.YEAR(display_width=4), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], name='authorship_ibfk_1'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='authorship_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_default_charset='utf8mb3',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
