"""Loan

Revision ID: 3dc2ba2e84a3
Revises: e9ff94640bfb
Create Date: 2022-05-31 17:06:46.703148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc2ba2e84a3'
down_revision = 'e9ff94640bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
