"""Loan

Revision ID: 5e61ee859777
Revises: 3dc2ba2e84a3
Create Date: 2022-05-31 17:08:26.375254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e61ee859777'
down_revision = '3dc2ba2e84a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
