"""Users-img

Revision ID: d9e7063d4181
Revises: 5e61ee859777
Create Date: 2022-05-31 17:12:55.529236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7063d4181'
down_revision = '5e61ee859777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
