"""AcessPoint

Revision ID: ea965982f313
Revises: 24a710850fc1
Create Date: 2022-06-06 16:12:01.213645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea965982f313'
down_revision = '24a710850fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
