"""Authority

Revision ID: eb6c372965bb
Revises: 
Create Date: 2022-06-06 15:38:32.974541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb6c372965bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authority', sa.Column('marc', mysql.JSON(), nullable=True))
    op.add_column('authority', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('authority', sa.Column('log', mysql.JSON(), nullable=True))
    op.drop_column('authority', 'schema')
    op.drop_column('authority', 'marc_record')
    op.drop_column('authority', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authority', sa.Column('format', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('authority', sa.Column('marc_record', sa.BLOB(), nullable=True))
    op.add_column('authority', sa.Column('schema', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('authority', 'log')
    op.drop_column('authority', 'type')
    op.drop_column('authority', 'marc')
    # ### end Alembic commands ###
