"""Loan

Revision ID: f031deedd4cb
Revises: 
Create Date: 2022-06-01 16:15:11.801980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f031deedd4cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('loan', sa.Column('log', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'log')
    op.drop_column('loan', 'status')
    # ### end Alembic commands ###
