"""AcessPoint

Revision ID: fce95aa91887
Revises: 1e5a1306e61e
Create Date: 2022-06-06 16:14:17.176795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fce95aa91887'
down_revision = '1e5a1306e61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_subject',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('authority_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('relation', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], name='item_subject_ibfk_1'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_subject_ibfk_3'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='item_subject_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_default_charset='utf8mb3',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
